site_name: Slackline Project Docs

theme:
  name: "material"

markdown_extensions:
  - attr_list

plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        position: "relative"
        width: "100%"
        padding-bottom: "56.25%"  # This value is for a 16:9 aspect ratio; adjust as needed
        overflow: "hidden"

extra_css:
  - css/custom.css

repo_url: https://github.com/HuMoN-Research-Lab/freemocap_slackline_project
