site_name: Slackline Project Docs

theme:
  name: "material"

markdown_extensions:
  - attr_list
  
plugins:
  - mkdocs-video
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"  

repo_url: https://github.com/HuMoN-Research-Lab/freemocap_slackline_project
